config/routes.rb
Planet::Application.routes.draw do
  get "planet/index"

  get "planet/contact"

  get "planet/ejemplo"
  
  root :to => "planet#index"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
  end

  def contact
  end
  
  def ejemplo
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planet</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planet/ejemplo.html.erb
<h1>ERb: Extended Ruby</h1>
El formato ERb o .erb es HTML extendido con anotaciones Ruby, delimitadas por <strong> &lt%
</strong> o <strong> &lt%= </strong> y <strong> %&gt </strong>, como en el siguiente ejemplo
<ul>
<li> Anotacion no visible: <% "esto NO se ve" %> </li>
<li> Anotacion visible: <%= "esto SI se ve" %> </li>
<li> Anotacion no visible: <% t=Time.now %> </li>
<li> Anotacion visible: <%= "hoy es: " + t.to_s %> </li>
</ul>
Tambien podemos generar un enlace al recurso (pagina) strong> Home </strong> con el
siguiente hiperenlace: <%= link_to('Home', planet_index_path) %>
Rails ejecuta el codigo Ruby y lo inserta en la pagina HTML antes de generar la pagina.

app/views/planet/index.html.erb
<h1> Wecome to the Planet Travel Site </h1>
<p>This site gathers information of touristic
sites from all over the world and should help
you to organize your trips and your holidays.
</p>
<%= image_tag('pedriza2-m.png') %>
<p>Feel free to use it for your
convenience and pleasure.</p>